name: espressocash_common
description: Espresso Cash Common Library
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  dfunc: ^0.9.0

dev_dependencies:
  mews_pedantic: ^0.25.0
